#!/bin/sh
echo "NON-STANDARD escape char is the backslash, not the usual Control+A"
echo "Control \, Control Q to quit"
echo "Control \, Control S to send a file from the local directory"

read -p " which tty (say 0 or 1 to complete /dev/ttyACM<#> here) (0 or 1): " device_number

picocom -e \\ -f n -p n -d 8 -b 57600 --imap lfcrlf --omap delbs,lfcr \
    --send-cmd "ascii-xfr -sn -l 5 -c 1" /dev/ttyACM${device_number}
exit 0

cat << _EOF__
  crlf : map CR --> LF
  crcrlf : map CR --> CR + LF
  igncr : ignore CR
  lfcr : map LF --> CR
  lfcrlf : map LF --> CR + LF
  ignlf : ignore LF
_EOF__

# end
